config/routes.rb
Wezolo::Application.routes.draw do
  resources :messages, :only => [:create, :index]
  get "profile/create"
  get "search/index"
  get "search/results", :to => "search#search_results"
  get "test" => "tumblr#show"
  resource :follows, :only => [:create, :destroy]
  resources :users do
    collection do
      put "update_password"
      get "edit_password"
    end
  end

  # :update_password => :put, :edit_password => :get
  resources :profiles, :only => [:edit, :update]
  resources :involvements, :only => [:new, :create, :edit, :update, :destroy]
  root :to => "home#landing"
  get '/home' => "home#home"
  get '/about' => "home#about"
  post '/login' => 'session#create', :as => "login"
  delete '/logout' => 'session#destroy', :as => "logout"
  get '/signup' => 'users#new', :as => "signup"
  post '/receive_callback' => "messages#receive_callback"
  match '/auth/google_oauth2/callback' => "session#create", :auth_provider => 'google'

  match '/auth/tumblr/callback' => "tumblr#connect", :auth_provider => 'tumblr'
  match '/tumblr/disconnect/' => "tumblr#disconnect"
  post "/tumblr/create_blog_and_posts" => "tumblr#create_blog_and_posts"

  post '/receive_callback' => "messages#receive_callback"

  match 'auth/blogger' => 'blogger#request_blogger_access'
  match '/auth/blogger/callback' => "blogger#authorize_blogger", :auth_provider => 'blogger'
  post "/blogger/create_blog_and_posts" => "blogger#create_blog_and_posts"
  match '/blogger/disconnect/' => "blogger#disconnect"

  post '/avatar_upload' => 'profiles#avatar_upload'

end

app/models/user.rb
class User < ActiveRecord::Base
  extend ExternalAuth
  include Tire::Model::Search
  include Tire::Model::Callbacks
  index_name "#{Tire::Model::Search.index_prefix}users"

  STATUSES_HASH = {"interested" => "Interested in Peace Corps","ipcv" => "Invited Peace Corps Volunteer","pcv" => "Current Peace Corps Volunteer","rpcv" => "Returned Peace Corps Volunteer"}

  has_secure_password

  attr_accessible :name, :password_digest, :status, :email, :password, :password_confirmation, :follower, :profile, :auth_status, :phone_number

  has_many :involvements
  has_many :countries, :through => :involvements

  accepts_nested_attributes_for :countries, :involvements

  validates :email, :uniqueness => true
  validate :valid_status?
  before_validation :downcase_status

  has_many :blogs
  has_many :posts, :through => :blogs

  has_many :follows, :as => :followable, :dependent => :destroy
  has_many :followers, :through => :follows

  has_many :followings, :class_name => "Follow", :foreign_key => "follower_id", :dependent => :destroy
  has_many :heroes, :through => :followings, :source => :followable, :source_type => "User"

  has_many :following_countries, :through => :followings, :source => :followable, :source_type => "Country"

  has_many :authorizations
  has_many :auth_providers, :through => :authorizations

  has_one :profile

  has_many :messages
  has_many :incomings
  has_many :responses

  after_create :follow_sam
  after_save :update_auth_status

  def self.statuses_hash
    STATUSES_HASH
  end

  def valid_status?
    if status
      errors.add(:status, "is not valid!") unless STATUSES_HASH[status]
    end
  end

  def downcase_status
    if status
      self.status = self.status.downcase
    end
  end

  def follow_sam
    if sam = User.find_by_email("samprofessional@gmail.com")
      self.heroes << sam
    end
  end

  AUTH_STATUSES = %w[guest incomplete user admin]

  AUTH_STATUSES.each do |auth_status|
    define_method "#{auth_status}_auth?" do
      AUTH_STATUSES.index(self.auth_status) <= AUTH_STATUSES.index(auth_status)
    end

    define_method "#{auth_status}?" do
      self.auth_status == auth_status
    end

  end

  tire do
    mapping do
      indexes :id,          :index => :not_analyzed
      indexes :name,        :boost => 100
      indexes :username
      indexes :status
      indexes :country_names
      indexes :user_bio
      indexes :user_location
      indexes :user_involvement_descriptions
      indexes :user_involvement_sectors
    end
  end

  def change_password(user)
    if self.authenticate(user[:current_password])
      self.update_attributes(:password => user["password"], :password_confirmation => user["password_confirmation"])
    else 
      self.errors.add(:What?, "Authentication of Current Password Failed")
    end
  end 

  def self.search(search_query)
    tire.search(:load => { :include => [:profile, :follows, {:involvements => :country}]}) do
      size 100
      query { string search_query, default_operator: "AND" } if search_query.present?
    end
  end

  def to_indexed_json
    to_json(methods: [:country_names, :user_bio, :user_location, :user_involvement_descriptions, :user_involvement_sectors])
  end

  def country_names
    countries.map(&:name) if self.countries.present?
  end

  def user_bio
    profile.bio if self.profile.present?
  end

  def user_location
    profile.location if self.profile.present?
  end

  def user_involvement_descriptions
    involvements.map(&:description) if self.involvements.present?
  end

  def user_involvement_sectors
    involvements.map(&:sector) if self.involvements.present?
  end

  def followed_posts(pagination = {})
    self.heroes_posts.paginate(:page => pagination[:page], :per_page => pagination[:per_page])
     # + self.countries_posts
   end

   def heroes_posts
    Post.includes({:blog => :user}).joins({:blog => {:user => :follows}}).where("follows.follower_id" => self.id).order("published_at DESC")
  end

  # method being deprecated
  def countries_posts
    # Post.joins({:blog => {:user => :follows}}).where("follows.follower_id" => self.id).order("published_at DESC")
    # sort_by_published_date(self.following_countries.includes(:posts).map(&:posts))
  end

  def user_followings_by_type
    self.followings.inject({}) do |follow_hash, following|
      type = following.followable_type
      id = following.followable_id
      follow_hash[type] ? follow_hash[type] << id : follow_hash[type] = [id]
      follow_hash
    end
  end

  def self.create_with_omniauth(auth)
    new_user = create! do |user|
      provider = set_provider(auth)
      user.authorizations << provider.authorizations.create(uid: auth["uid"])
      user.name = auth["info"]["name"]
      user.email = auth["info"]["email"]
      user.password = SecureRandom.hex(10)
    end
    new_user.create_profile(photo_url: auth["info"]["image"])
    new_user
  end

  def update_auth_status
    self.update_attributes(:auth_status => "user") if self.status == "interested" && self.auth_status == "incomplete"
  end

  private

  def sort_by_published_date(array)
    array.flatten.sort_by {|post| post.published_at}.reverse
  end

  def self.phone_number(user_id)
    User.find(user_id).phone_number
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    @user.countries.build
  end

  def create
    #refactor the form so that you don't have pass all these params
    user = User.new(email: params[:email], password: params[:password],password_confirmation: params[:password_confirmation], name: params[:name], status: params[:status].first)
    if user.save
      user.create_profile
      set_session(user)
      render :json => {:redirect => "/home"}
    else
      @error = user.errors.full_messages
      render :json => {:error => @error}, :status => :unprocessable_entity
    end
  end

  def show
    @user = User.includes(:profile, :involvements => :country).find(params[:id]).decorate

    authorize! :read, @user
  end

  def edit_password
    @user = current_user
  end

  def update_password
    current_user.change_password(params[:user])
    if current_user.errors.any?
      flash[:error] = current_user.errors.full_messages.join(", ")
    else
      flash[:notice] = "Password Change!"
    end
    redirect_to edit_password_users_path
  end

  def destroy
  end

end

app/helpers/users_helper.rb
module UsersHelper
  def render_user_box(user)
    render :partial => "users/user", :locals => {:user => user}
  end
end

app/views/users/_user.html.haml
.user-box.form-effects.form-margins.span6
  .row
    .span2.img-container
      = image_tag avatar_url(user), :class => "img-polaroid"
    .offset1.info-section.pagination-centered
      %h4= link_to (user.name), user
      %p= status = user.status.upcase if user.status
      .btn.btn-info.btn-small= current_user.follow_link(user)
  .row
    - unless status == "INTERESTED"
      .involvement-list
        %h6 Service Details:
        - user.involvements.each do |inv|
          .involvement
          %p= "#{inv.country.name}, #{inv.sector.titleize}, #{date_to_year(inv.start_date)} - #{date_to_year(inv.end_date)}"

app/views/users/create.js.erb
#Review: Is this used?

app/views/users/edit_password.html.haml
.content
  .container.green-full-width
    .form-effects.form-margins.basic-info-edit
      %h1 User settings
      = form_for @user, :url => update_password_users_path, :method => :put do |f|
        = f.label :current_password
        = f.password_field :current_password, :required => true
        = f.label :password
        = f.password_field :password, :required => true
        = f.label :password_confirmation
        = f.password_field :password_confirmation, :required => true
        = f.submit "Change Password", :class => "btn btn-danger"
    
        
        - if flash[:error]
          .alert.alert-error
            %a.close{"data-dismiss"=>"alert"}
            %h4.alert-heading WeZooNOoOoOO!
            %p= flash[:error]
        - if flash[:notice]
          .alert.alert-success
            %a.close{"data-dismiss"=>"alert"}
            %h4.alert-heading WEZOLO SUCEESS!
            %p= flash[:notice]

app/views/users/show.html.haml
.content
  .container
    .form-effects.form-margins
      .row
        .offset1.span6
          %h3= @user.name
        .offset2.span2
          - unless current_user == @user
            .pull-right.btn.btn-info.btn-small= current_user.follow_link(@user.object)
      .row.bottom-spacer
        .offset1.span3
          = image_tag avatar_url(@user), :class => "avatar img-polaroid bottom-spacer"
          - if current_user == @user
            %a#upload{:href => "#"} Upload/Change profile pic
        .span7.profile
          %table.table
            %tr.info
              %th Basic Info
              %th.align-right
                - if can? :update, @user.profile
                  = link_to "Edit", "#basic-edit-info-modal", {"data-toggle" => "modal"}
            %tr
              %td Status:
              %td
                .user-info
                  = User.statuses_hash[@user.status]
            %tr
              %td Phone:
              %td
                .user-info
                  = @user.phone_number
            %tr
              %td Location:
              %td
                .user-info
                  = @user.profile.location
            %tr
              %td Bio:
              %td
                .user-info
                  = @user.profile.bio
      .row
        .offset1.span3
          %table.table
            %tr.following
              %th Following
          .thumbnails
            - @user.heroes.each do |hero|
              = link_to((image_tag avatar_url(hero), :title => hero.name, :class => "thumbnail"), hero)
        .span7.profile
          %table.table
            %tr.info
              %th{:colspan => 3} Connect Your Blog
            %tr
              %td
                Blogger:
                = @user.display_blog_section "blogger"
            %tr
              %td
                Tumblr:
                = @user.display_blog_section "tumblr"
      .row
        - if @user.status != "interested"
          .offset4.span7.profile#service-details
            %table.table
              %tr.info
                %th Service Details
                %th.align-right
                  - if can? :add_involvement, @user
                    = link_to "Add", "#service-details-add-modal", {"data-toggle" => "modal"}
            -unless @user.involvements.empty?
              - @user.involvements.order("end_date DESC").each_with_index do |i, index|
                = render :partial => "layouts/error"
                %table.table
                  %tr
                    %td
                    %td.pull-right
                      - if can? :update, i
                        =link_to "Edit", "#service-details-edit-modal-" + index.to_s, {"data-toggle" => "modal"}
                        ="#{" | "}"
                        =link_to("Delete", involvement_path(i), :method => :delete, :confirm => "Are you sure you want to delete these service details?", :class => "alert-heading")
                        .widgets= render "/layouts/modal", :title => "Edit Service Details", :id => "service-details-edit-modal-"+index.to_s , :body => render("involvements/form", :involvement => i)
                  %tr
                    %td.small Country:
                    %td.large
                      .user-info
                        = i.country.name if i.country
                  %tr
                    %td Description:
                    %td
                      .user-info
                        = i.description
                  %tr
                    %td Sector:
                    %td
                      .user-info
                        = i.sector
                  %tr
                    %td Start Date:
                    %td
                      .user-info
                        = date_to_year(i.start_date)
                  %tr
                    %td End Date:
                    %td
                      .user-info
                        = date_to_year(i.end_date)
                %hr


.widgets
  - if can? :update, @user.profile
    = render "/layouts/modal", :title => "Basic Info", :id => "basic-edit-info-modal", :body => render("profiles/form", :profile => @user.profile)
  - if can? :add_involvement, @user
    = render "/layouts/modal", :title => "Add New Service Details", :id => "service-details-add-modal" , :body => render("involvements/form", :involvement => Involvement.new)
  = render "/layouts/modal", :title => "Confirm Blog", :id => "confirm-blog-modal", :body => "", :blogs => @blogs