config/routes.rb
Wezolo::Application.routes.draw do
  resources :messages, :only => [:create, :index]
  get "profile/create"
  get "search/index"
  get "search/results", :to => "search#search_results"
  get "test" => "tumblr#show"
  resource :follows, :only => [:create, :destroy]
  resources :users do
    collection do
      put "update_password"
      get "edit_password"
    end
  end

  # :update_password => :put, :edit_password => :get
  resources :profiles, :only => [:edit, :update]
  resources :involvements, :only => [:new, :create, :edit, :update, :destroy]
  root :to => "home#landing"
  get '/home' => "home#home"
  get '/about' => "home#about"
  post '/login' => 'session#create', :as => "login"
  delete '/logout' => 'session#destroy', :as => "logout"
  get '/signup' => 'users#new', :as => "signup"
  post '/receive_callback' => "messages#receive_callback"
  match '/auth/google_oauth2/callback' => "session#create", :auth_provider => 'google'

  match '/auth/tumblr/callback' => "tumblr#connect", :auth_provider => 'tumblr'
  match '/tumblr/disconnect/' => "tumblr#disconnect"
  post "/tumblr/create_blog_and_posts" => "tumblr#create_blog_and_posts"

  post '/receive_callback' => "messages#receive_callback"

  match 'auth/blogger' => 'blogger#request_blogger_access'
  match '/auth/blogger/callback' => "blogger#authorize_blogger", :auth_provider => 'blogger'
  post "/blogger/create_blog_and_posts" => "blogger#create_blog_and_posts"
  match '/blogger/disconnect/' => "blogger#disconnect"

  post '/avatar_upload' => 'profiles#avatar_upload'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  QUERY_TYPES = ["country", "sector", "status", "follow", "all"]

  def landing
  end

  def home
    authorize! :read, Post
    if params[:query_type] == nil || !QUERY_TYPES.include?(params[:query_type])
      @newsfeed = current_user.followed_posts({:page => params[:page], :per_page => 10})
    else
      @newsfeed = Post.find_posts(params[:query_type], params[:query_string], {:page => params[:page], :per_page => 10})
    end
  end

  def valid_query?
  end
  
  def about  
  end
end

app/views/home/_fab.html.haml
#fab-modal.modal.hide.fade.profile-modal{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-header
    %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
    %h3#myModalLabel Fab Mackojc
  .modal-body.profile-body.container-fluid
    .upper-half.row-fluid
      .headshot-box.span5
        =image_tag "fab-mackojc-headshot.png", {:class => "member-headshot"}
      .details-box.span7
        %h5 Info:
        %ul
          %li
            %span.subject Hometown:
            %span.detail Melbourne, Australia
          %li
            %span.subject Education:
            %span.detail Monash University / Dev Bootcamp
          %li
            %span.subject Known for:
            %span.detail Reminding us to push to the development branch
        =link_to image_tag("github.png", {:class => "logo"}), "http://github.com/fab"
        =link_to image_tag("linkedin.png", {:class => "logo"}), "http://linkedin.com/in/fabsays"
    .row-fluid
      .bios-box
        %p I break the stereotype for the kind of person you’d expect to have done a math major at University. I’m very outgoing and quite energetic. When I’m completely myself I tend to make people laugh. I’m always trying to improve how I spend my time here on Earth and make the most of every experience. I’m also passionate about exploring and am a big fan of exposing myself to new things. I believe that you should follow your dreams and be living a life you love. Do what you find interesting, even if that’s more risky. Life is more exciting that way.

app/views/home/_sam.html.haml
#sam-modal.modal.hide.fade.profile-modal{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-header
    %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
    %h3#myModalLabel Steven "Sam Samskies" Miyakawa
  .modal-body.profile-body.container-fluid
    .upper-half.row-fluid
      .headshot-box.span5
        =image_tag "steven-miyakawa-terminator.png", {:class => "member-headshot"}
      .details-box.span7
        %h5 Info:
        %ul
          %li
            %span.subject Peace Corps Status:
            %span.detail Returned Peace Corps Volunteer
          %li
            %span.subject Origin:
            %span.detail Kaneohe, Hawaii
          %li
            %span.subject Education:
            %span.detail University of Hawaii / Dev Bootcamp
          %li
            %span.subject Known for:
            %span.detail Being more popular than "MySpace Tom"
        =link_to image_tag("github.png", {:class => "logo"}), "http://github.com/samsamskies"
        =link_to image_tag("linkedin.png", {:class => "logo"}), "http://linkedin.com/pub/steven-miyakawa-%22sam%22/66/440/3b2"
    .row-fluid
      .bios-box
        %p If we we weren't programming so hard we would tell you more about ourselves. Maybe a life story or some detailed information about how we came to be in this world. Sadly ain't no body got time for that. so I'll just copy and paste this twice. If we we weren't programming so hard we would tell you more about ourselves. Maybe a life story or some detailed information about how we came to be in this world. Sadly ain't no body got time for that. so I'll just copy and paste this twice.

app/views/home/_sidney.html.haml
#sidney-modal.modal.hide.fade.profile-modal{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-header
    %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
    %h3#myModalLabel Sidney Zhang
  .modal-body.profile-body.container-fluid
    .upper-half.row-fluid
      .headshot-box.span5
        =image_tag "sidney-zhang-headshot.png", {:class => "member-headshot"}
      .details-box.span7
        %h5 Info:
        %ul
          %li
            %span.subject Hometown:
            %span.detail Melbourne, Australia
          %li
            %span.subject Education:
            %span.detail University of Melbourne / Dev Bootcamp
          %li
            %span.subject Known for:
            %span.detail Eager Loading
        =link_to image_tag("github.png", {:class => "logo"}), "http://github.com/sidazhang"
        =link_to image_tag("linkedin.png", {:class => "logo"}), "http://linkedin.com/in/sidneyzhang"
    .row-fluid
      .bios-box
        %p If we we weren't programming so hard we would tell you more about ourselves. Maybe a life story or some detailed information about how we came to be in this world. Sadly ain't no body got time for that. so I'll just copy and paste this twice. If we we weren't programming so hard we would tell you more about ourselves. Maybe a life story or some detailed information about how we came to be in this world. Sadly ain't no body got time for that. so I'll just copy and paste this twice.

app/views/home/_stephen.html.haml
#stephen-modal.modal.hide.fade.profile-modal{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-header
    %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
    %h3#myModalLabel Stephen Nguyen
  .modal-body.profile-body.container-fluid
    .upper-half.row-fluid
      .headshot-box.span5
        =image_tag "stephen-nguyen-headshot.png", {:class => "member-headshot"}
      .details-box.span7
        %h5 Info:
        %ul
          %li
            %span.subject Hometown:
            %span.detail Chantilly, Virginia
          %li
            %span.subject Education:
            %span.detail Virginia Commonwealth University / Dev Bootcamp
          %li
            %span.subject Known for:
            %span.detail Weird analogies & designing fancy about us pages
        =link_to image_tag("github.png", {:class => "logo"}), "http://github.com/stephenitis"
        =link_to image_tag("linkedin.png", {:class => "logo"}), "http://linkedin.com/in/stephenhnguyen/"
    .row-fluid
      .bios-box
        %p I've spent my education, sweat, and time devoted to making a impact on my world. Born in a loving middle class family in suburban Virginia, I have developed a profound passion for community service, a respect for science, and a drive to help solve relevant problems in the world through what ever means possible. I am a rubyist who is working towards becoming a full stack web developer in short time. I’m apart of the Spring 2013 Cohort at Dev Bootcamp in San Francisco, California. My more reflective and sometimes quirky blog sits over at <a href="www.WhereIsStephen.com">www.whereisstephen.com</a>

app/views/home/about.html.haml
%body
  .about-container
    .team-box
      .div.member-profile
        =link_to image_tag("fab.png", {:class => "team-member"}), "#fab-modal", {"data-toggle" => "modal"}
      .div.member-profile
        =link_to image_tag("sam.png", {:class => "team-member"}), "#sam-modal", {"data-toggle" => "modal"}
      .div.member-profile
        =link_to image_tag("stephen.png", {:class => "team-member"}), "#stephen-modal", {"data-toggle" => "modal"}
      .div.member-profile
        =link_to image_tag("sidney.png", {:class => "team-member"}), "#sidney-modal", {"data-toggle" => "modal"}
    %h1 Team Wezolo
  .container.marketing.top-spacer.story
    %h2 Our Story
    %p Dev Bootcamp is hard but Africa is harder. Sam Samskies along with a team of bright engineers embarked on a ridiculous journey to build Wezolo, a platform where you can live the Peace Corps life. Twilio yo self.
  .container.marketing.top-spacer.story
    %h2 The Team
    %p Deep in the darkest corners of DBC...The team aka the Peace Mafia, consisting of <a href="http://www.wezolo.com/about#sam-modal" data-toggle="modal">Steven "Sam Samskies" Miyakawa</a>, <a href="http://www.wezolo.com/about#stephen-modal" data-toggle="modal">Stephen Nguyen</a>,  <a href="http://www.wezolo.com/about#sidney-modal" data-toggle="modal">Sidney Zhang</a>, and <a href="http://www.wezolo.com/about#fab-modal" data-toggle="modal">Fab Mackojc</a> was created in response to the evil and the darkness that seeks to prevail over the world. With our power to develop great web apps and big hearts we will change the world or lose sleep trying.
  .container.marketing.top-spacer.story
    %h2 The App
    %p Our web app is run by inguenity, teamwork, and cats. There are lots of cats involved. High tech kittens from outer space who have come back through time to nip at code.
    %footer.top-spacer
      %p.pull-right
        %a{:href => "#"} Back to top
      %p
        © 2013 Peace Mafia ·
        %a{:href => "#"} Privacy
        ·
        %a{:href => "#"} Terms
        ·
        =link_to "About", about_path
        | Team photo by
        %a{:href => "http://avalonemerson.com"} Avalon Emerson
        |
        %a{:href => "mailto:contact@wezolo.com"} Email us

= render :partial => "home/fab"
= render :partial => "home/sam"
= render :partial => "home/sidney"
= render :partial => "home/stephen"

app/views/home/home.html.haml
.content
  .container.news-container
    .row.span10
      %h1 What's Going On?
      .well.sidebar-nav-fixed
        .inner-sidebar
          %ul.nav.nav-list
            %p Posts by Users you Follow
            %li
              = link_to "Users You Follow(default option)", "/home"
            %p Posts by Country of Service
            %li
              = select "query", "country_id", Country.all.map {|c| [c.name, c.id]}, {:include_blank => true, :prompt => 'Select a Country'}, {:class => "country-filter"}
          %ul.nav.nav-list
            %p Posts by Peace Corp Status
            - User.statuses_hash.each do |acr, text|
              %li= link_to text, home_path(query_string: acr, :query_type => "status")
          %ul.nav.nav-list
            %p Posts by Sector
            - Involvement.sectors.each_with_index do |sector_name, index|
              - if index < 4
                %li= link_to sector_name.titleize, home_path(query_string: sector_name, :query_type => "sector")
          %ul.nav.nav-list
            - Involvement.sectors.each_with_index do |sector_name, index|
              - if index >= 4
                %li= link_to sector_name.titleize, home_path(query_string: sector_name, :query_type => "sector")
    -@newsfeed.each do |post|
      - user = post.blog.user
      .form-effects.form-margins.span10
        .post-container
          .row
            .pull-left.vertical-align
              .thumbnail
                = link_to((image_tag avatar_url(user), :title => user.name), user)
            .span7
              %h3= post.title
              %p.published-date= "Posted by #{user.name} on #{post_date_and_time(post.published_at)}"
              %p= post.body.html_safe
    .hidden=will_paginate @newsfeed

app/views/home/landing.html.haml
%body
  .landing-container
    .error-notice
      - if flash[:notice]
        = flash.now[:notice]
    .container
      .carousel-caption
        %h1 Live The Peace Corps Life
        %p.lead Welcome to Wezolo, where you can connect with past, present and future Peace Corps volunteers! We're a family, so let's help each other.
        =link_to "Sign up today", "#signupModal", {"data-toggle" => "modal", :class => "btn btn-large btn-primary"}
      .row.pagination-centered.top-spacer
        %a{:href => "#bottom"}
          = image_tag "down-arrow.png", :class => "img-circle"
  .container.marketing.top-spacer#bottom
    .row
      .span4
        = image_tag "discover.jpg", :class => "img-circle"
        %h2 Discover
        %p Thinking of joining the Peace Corps? Check out our "What's Going On?" feed. Our feed is populated by our users Blogger/Blogspot and Tumblr blogs. Everything in one place. BOOM!
        %p
      .span4
        = image_tag "connect.jpg", :class => "img-circle"
        %h2 Connect
        %p Easily search for other users by name, country of service, and sector. Make new friends and/or find your old buddies. WATDATDATDATDATDUKEN!
        %p
      .span4
        = image_tag "nokia.jpg", :class => "img-circle"
        %h2 Communicate
        %p Stuck in a village with no data network? Check out our SMS tool that lets you send a question to our site via text messaging. When users respond to your question, you'll get the responses via SMS. BOOYAH!
        %p
    %footer.top-spacer
      %p.pull-right
        %a{:href => "#"} Back to top
      %p
        © 2013 Peace Mafia ·
        %a{:href => "#"} Privacy
        ·
        %a{:href => "#"} Terms
        ·
        =link_to "About", about_path
        | Cover photo by
        %a{:href => "mailto:sworthington@gmail.com"} Scott Worthington
        |
        %a{:href => "mailto:contact@wezolo.com"} Email us