config/routes.rb
Wezolo::Application.routes.draw do
  resources :messages, :only => [:create, :index]
  get "profile/create"
  get "search/index"
  get "search/results", :to => "search#search_results"
  get "test" => "tumblr#show"
  resource :follows, :only => [:create, :destroy]
  resources :users do
    collection do
      put "update_password"
      get "edit_password"
    end
  end

  # :update_password => :put, :edit_password => :get
  resources :profiles, :only => [:edit, :update]
  resources :involvements, :only => [:new, :create, :edit, :update, :destroy]
  root :to => "home#landing"
  get '/home' => "home#home"
  get '/about' => "home#about"
  post '/login' => 'session#create', :as => "login"
  delete '/logout' => 'session#destroy', :as => "logout"
  get '/signup' => 'users#new', :as => "signup"
  post '/receive_callback' => "messages#receive_callback"
  match '/auth/google_oauth2/callback' => "session#create", :auth_provider => 'google'

  match '/auth/tumblr/callback' => "tumblr#connect", :auth_provider => 'tumblr'
  match '/tumblr/disconnect/' => "tumblr#disconnect"
  post "/tumblr/create_blog_and_posts" => "tumblr#create_blog_and_posts"

  post '/receive_callback' => "messages#receive_callback"

  match 'auth/blogger' => 'blogger#request_blogger_access'
  match '/auth/blogger/callback' => "blogger#authorize_blogger", :auth_provider => 'blogger'
  post "/blogger/create_blog_and_posts" => "blogger#create_blog_and_posts"
  match '/blogger/disconnect/' => "blogger#disconnect"

  post '/avatar_upload' => 'profiles#avatar_upload'

end

app/views/layouts/_error.html.haml
- if flash[:error]
  .row
    .alert.alert-error.span6
      %a.close{"data-dismiss" => "alert"}x
      %h4.alert-heading WeZooNOoOoOO
      %p= flash[:error]

app/views/layouts/_login.html.haml
#loginModal.modal.hide.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-header
    %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
    %h3#myModalLabel Wezolo Login
  .modal-body
    %a{:href => '/auth/google_oauth2'}
      %img#google-login-button{:src => 'https://developers.google.com/+/images/branding/sign-in-buttons/Red-signin_Long_base_44dp.png'}
    %h4.top-spacer Or fill out the following:
    =form_tag login_path, :method => :post, :remote => true do
      = email_field_tag :email, nil, {:required => true, :placeholder => "Email"}
      = password_field_tag :password, nil, {:required => true, :placeholder => "Password"}
      = submit_tag "Sign in", :class => "btn btn-primary loginmein"
  .alert.alert-error.login-error

app/views/layouts/_modal.html.haml
.modal.hide.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1", :id => id}
  .modal-header
    %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
    %h3#myModalLabel 
      = title
  .modal-body
    = body

app/views/layouts/_nav.html.haml
.navbar-wrapper
  .container
    .navbar.navbar-inverse.navbar-fixed-top
      .navbar-inner
        -if current_user
          = link_to "Wezolo", home_path, :class => "brand"
        - else
          = link_to "Wezolo", root_path, :class => "brand"
        %ul.nav
          %li.signin
            =link_to "About", about_path
          %li.signin.pull-right
            - unless current_user
              =link_to "Log in", "#loginModal", {"data-toggle" => "modal"}
          - if current_user
            %li.dropdown.pull-right
              %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                =current_user.email
                %b.caret
              %ul.dropdown-menu
                %li
                  =link_to "Profile", user_path(current_user)
                %li
                  =link_to "What's Going On?", home_path
                %li
                  =link_to "Volunteer Questions", messages_path
                %li
                  =link_to "Find Volunteers", search_index_path
                %li.divider
                %li
                  =link_to "Settings", edit_password_users_path
                %li
                  =link_to "Log out", logout_path, :method => "delete"
            %li.search.pull-right
              =form_tag search_results_path, :method => :get, :class => "form-search" do
                .input-append
                  =text_field_tag "search", nil,:class => "search-query-8 span3 search-query", :placeholder => "Search Volunteers"
                  %button.btn.btn-small{:type => "submit"}
                    %span.fui-search.fui-icons-h

app/views/layouts/_signup.html.haml
#signupModal.modal.hide.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-header
    %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
    %h3#myModalLabel Create a Wezolo Account!
  .modal-body
    %a{:href => '/auth/google_oauth2'}
      %img#google-login-button{:src => 'https://developers.google.com/+/images/branding/sign-in-buttons/Red-signin_Long_base_44dp.png'}
    %h4.top-spacer Or fill out the following:
    =form_tag users_path, :method => :post, :remote => true do
      = text_field_tag :name, nil, {:required => true, :placeholder => "Full Name"}
      = email_field_tag :email, nil, {:required => true, :placeholder => "Email"}
      = label_tag :status
      = select :status, nil, User.statuses_hash.map{|k,v| [v,k]}, {:prompt => true}, {:required => true}
      %br
      = password_field_tag :password, nil, {:required => true, :placeholder => "Password"}
      = password_field_tag :password_confirmation, nil, {:required => true, :placeholder => "Password Confirmation"} 
      = submit_tag "Sign Up", {:class =>"btn btn-primary createaccount"}
    / %button.btn.btn-primary Log in
  .alert.alert-error.signup-error

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wezolo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <script src="//api.filepicker.io/v1/filepicker.js" type="text/javascript"></script>
  <meta content="authenticity_token" name="csrf-param" />

  <%= csrf_meta_tags %>
</head>
<body>
<%= render :partial => "layouts/nav" %>
<%= render :partial => "layouts/login" %>
<%= render :partial => "layouts/signup" %>
<%= yield %>

</body>
</html>